akiran/react-slick

README.md, docs/demos.jsx, lib/default-props.js, lib/inner-slider.jsx, lib/mixins/helpers.js
Hey,
I've implemented afterChange which is a property passing in via settings which is expected to be a function with a single parameter of the index which we have just navigated too.
I've also added this to the demo page, but it simply prints to the console with highlighted colours in chrome.
I've implemented the Initial Slide property (as requested on https://github.com/akiran/react-slick/issues/15)
There was also a bug with the Centre slider when infinite wasn't enabled, and you couldn't navigate to the final slide.
Cheers
Stephen Roberts
=> Adding afterChange function, InitialSlider and fixing a bug when using centre mode and not infinate

lib/mixins/helpers.js
props is passed into initialize and initialize is not being bound to the places it's called so using props instead of this.props gives the correct initialslide for the current props being passed in.
This causes a problem of if you're passing in initialSlide, and whenever a state changes out of the component, the component will be one slide behind because it was using the previously set this.props.initialSlide instead of the current props.initialSlide passed in.
=> Change this.props.initialSlide to props.initialSlide in initialize

package.json
This `>` should have been a `>=` to permit version 0.12
=> Work with React 0.12 and 0.13

lib/mixins/helpers.js
Otherwise iOS 8 Safari is transitioning `transform`, but applying `-webkit-transform`
(and ignoring `transform`).
=> Apply a -webkit-transition for the -webkit-transform.

src/mixins/helpers.js
The current version will still loop from one end of the slideshow to the other, even when the `infinite` property is set to `false`.
This pull request fixes that :boom:
=> fix logic when infinite = false

README.md, src/slider.jsx
- porting this feature from the original slick carousel
- setting disables the slick carousel for the selected breakpoint (nested HTML not modified/slicked)
- responsive setting section of README updated with an example usage
=> add support for 'unslick' responsive breakpoint setting

.npmignore
Since people may prefer to add compiled files in script tags instead of using something like browserify/webpack.
Relates to #76
=> Removed "dist" directory from npmignore

src/inner-slider.jsx
While using react-slick in my application, this warning message occurred periodically:
`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.`
Seems like it is resulted from an uncleared timer, `autoPlayTimer`, while using the `autoplay` feature, and adding the `window.clearTimer` in `componentWillUnMount` fixes the problem.
=> fix autoPlayTimer not cleared after component unmounted

src/track.jsx
took @vramana's approach.
now the center slide and all of its clones receive the 'slick-center' class.
=> fix for centerMode warping #72

docs/demos.jsx, src/default-props.js, src/mixins/helpers.js
I need this functionality, which was removed in https://github.com/akiran/react-slick/commit/f56590a2c4e5d74a24617b2a233262babc010ad1
Reasons:
-  In some cases it's better for usability to have the slide not change before animation has been finished
- There's an issue with with react-slick; if user keeps clicking next/prev arrows in infinite scrolling slider, before animation has finished and animation duration is reasonably hight (say 500 ms),  the slider will end up with empty items. This is one workaround.
- The change was introduced to fix https://github.com/akiran/react-slick/issues/140 but the issue is still open.
However, I'm not sure if using waitForAnimate is the correct property to use but it's a start and seems to work.
=> Very simple implementation for waitForAnimate property

package.json
npm looks for binaries inside `./node_modules/.bin` implicitly when it runs scripts so these paths are redundant
=> Remove references to `./node_modules/.bin` in npm scripts

src/dots.jsx
You took my attention to these lines in my last PR: https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L54-L56
and I noticed this time around that the default for the dots content is actually { i + 1 } instead of { i }. So this basic change actually matches the default dot content for slick.
Here's a screenshot of the content from the first dot on slicks webpage.
This does, however, affect backwards compatibility. How would you like to proceed?
Also, I'm working on the customPaging option in a separate branch.
=> matching default functionality to slick

src/inner-slider.jsx
> Warning message "Iterable.length has been deprecated, use iterable.size or iterable.count()" when using ImmutableJS list as items
When using a immutable collection with react-slick you will receive the above error message. This pr fixes the issue by changing the collection measurement from length the to use the React.Children.Count.
P.S. This is my very first pull request so please let me know if I need to change anything.
=> Change this.props.children.length to use React.Children.count() instead.

src/track.jsx
Fix for #279 
Skip auto-generated keys for slides if key already exist.
=> Keep original keys for slides

package.json
When running npm install:
```
You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.
npm uninstall babel
npm install babel-cli
See http://babeljs.io/docs/usage/cli/ for setup instructions.
```
=> Replace babel with babel-cli

.eslintrc
Atom complains:
```
Configuration for rule "global-strict" is invalid:
Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed 'true').
```
=> Replace boolean values in eslint config with integers as per the docs

src/inner-slider.jsx
fixes #321 
Note this would mean hiding `:only-child` for people who _don't_ want a single dot to be displayed
=> dots: true should always show dots, regardless of number of images

src/mixins/helpers.js
beforeChange / afterChange are bugged when fade is enabled (values are off), using targetSlide fixes that.
=> Fixes the beforeChange / afterChange when fade = true

docs/demos.jsx, examples/UnevenSetsFinite.js, examples/UnevenSetsInfinite.js, src/mixins/trackHelper.js
Presently, when ```infinite = false```, and the carousel has an uneven set, it will slide to the end of the number of slides to show, even if the carousel doesn't have enough items to fill the space. Example below:
The correct behavior (IMO) should be the same as if infinite were ```true```  - scroll until the end of the visible item, like this:
This PR does the following: 
1. adds an example of an uneven set that is not infinite, and;
2. sets the offset so that it will only scroll to the last visible item.
=> Only scroll to the last visible item when a set is uneven and infinite = false

examples/SlickGoTo.js
I've noticed that, in the SlickGoTo example, there is an input with the initialValue property set to 0. If I'm not mistaken, that initialValue prop should be defaultValue instead.
Note to self: I also have [#449](https://github.com/akiran/react-slick/pull/449) open, will rebase if one or the other is merged/accepted first.
=> Changed input's initialValue prop to defaultValue.

src/inner-slider.jsx
Passing slide index of zero doesn't work, because zero behaves as falsy. Type checking fixes the problem.
=> passing 0 slide index slickGoTo() bugfix

src/default-props.js
Which is described in [README](https://github.com/akiran/react-slick/blob/master/README.md)
=> Default`pauseOnHover` should be true

src/mixins/helpers.js
Hi,
When the slider has infinite mode == false and we slide too far, the slider doesn't refresh the position of the slides on swipe end, so they are stuck in the middle instead of being moved back to the original position. The fix is that even if the slide number doesn't change, we should still update the state to refresh the position.
Before PR:
After PR:
=> Fixes Swipe too far in infinite == false did not reset to previous position

src/inner-slider.jsx, src/track.jsx
If `!focusOnSelect` then `new Function` is executed. This is actually
code evaluation. Use an empty function instead.
=> Fix for #461: avoid code evaluation when !focusOnSelect

README.md, docs/demos.jsx, examples/SwipeToSlide.js, examples/VerticalSwipeToSlide.js, src/mixins/event-handlers.js
This is a basic implementation of the 'swipeToSlide' property, including readme and demo. A similar pull request for this feature already exists, but I've implemented the feature myself with a view to making the 'swipeToSlide' property compatible with the vertical mode and vertical swiping, something that is not present in the original slick carousel library. The following briefly details the changes made:
- Description of 'swipeToSlide' added to the readme.
- SwipeToSlide and VerticalSwipeToSlide examples added to the demo.
- getSlideCount, checkNavigable and getNavigableIndexes methods from the original library reimplemented.
- These methods used to provide swipeToSlide functionality in the swipeEnd method.
- If swipeToSlide is set to false the behaviour here is no different, and the …
=> SwipeToSlide with Vertical Integration

src/mixins/helpers.js
Fixed issue #465, which originates in the helpers file in the update method specifically. For whatever reason the bug is not highlighted by calls to the initialize helper.
- slideWidth used trackWidth directly in calculations, but this.track is not the same thing as this.
=> Fixed #465.

src/inner-slider.jsx
There was a lot of flickering when using responsive option and changing size with autoplay enabled.
This fix eliminates the problem.
=> fixed flickering on window  resize with responsive and autoplay

src/mixins/trackHelper.js
We currently see that lots of our users get an error from the slick carousel.
We are using `variableWidth: true`, `centerMode: true`, `infinite: false` and when the user swipes the content to the right to show the non-existing slide to the left it causes the following error:
```
TypeError: undefined is not an object (evaluating 'targetSlide.offsetWidth')
```
=> Error when targetLeft is not available

src/mixins/event-handlers.js
Issue: Having items with click handlers inside react-slick do not get
triggered when the option swipe is set to false.
This is because `swipeEnd` called `preventDefault()`.
Tested on: iPad mini 4 & iPad Air 2 Simulator
=> Only suppress default if swipe is enabled

README.md
There was a lib breaking change, and arrows should now be passed as Element instead of Component, see https://github.com/akiran/react-slick/issues/458
=> Arrows should be Element instead of Component

src/mixins/helpers.js
We are using react-slick for an image carousel and our mocha tests are throwing random NaN console.logs:
```
Warning: `NaN` is an invalid value for the `width` css style property. Check the render method of `ProductDetailImage`.
```
Our tests are not currently failing, but we would like this message to disappear.
We've narrowed it down to the **getWidth** and **getHeight** functions returning undefined because our test images are mocked.
**elem.getBoundingClientRect().width** and **elem.getBoundingClientRect().height** are returning 0, but falling back to **elem.offsetWidth** and **elem.offsetHeight** which are returning undefined. We felt this should fallback to 0 in that case.
=> Adds fallback 0 to getWidth and getHeight in case of undefined.

src/inner-slider.js, src/mixins/event-handlers.js
When switch slider by clicking dots inside Slider container, the mouse enter will never trigger, so even the mouse point is still stay inside Slider container, the Slider won't stop.
demo: https://ant.design/components/carousel/#components-carousel-demo-autoplay
close ant-design/ant-design#4272
=> Fix pauseOnHover never trigger again

src/arrows.js
My use case for this was to change the last slide's arrow from saying "Next" to "Done". The default arrows have access to these props and use them to set a disabled class. It seems only fair that custom arrows have these props as well 😄 .
I found it difficult to use the `beforeChange` handler alone to achieve this without causing the entire carousel to re-render. That was bad because it prevented the slide transitions from animating.
=> Pass currentSlide and slideCount props to arrow components

src/mixins/event-handlers.js
Call preventDefault during animation, otherwise it will trigger native swipe event, such as tab switch.
=> Prevent native swipe event during animation

README.md
Hey, many developers are used to running only ```npm install package-name``` to add a package. We were two developers to forget importing the styles and to get an unexpectedly broken slideshow.
(You might also consider adding a comment line in the JsFiddle to remind us to get the external css files imo)
It's a silly mistake but it can be very puzzling and made us waste 1 hour each !
I think this small warning can save time to people \o/ what do you think guys ?
=> Add a warning sign

src/slider.js
1.  In some cases, it's necessary to add styles to wrapper of destroyed slider. It's better to add className to existing wrapper, than wrap it to another one and write something like:
```css 
.wrapper > div { display: flex; ... } 
```
2. To avoid duplication of responsive logic, it'll be easier to write:
```css 
.wrapper.unslicked { display: flex; ... } 
```
=> Added className to wrapper of destroyed slider

src/track.js
I presume this was a mistake because we have booleans either side of the OR? Cheers.
=> change bitwise OR to a logical OR

README.md, package.json
First of all thanks for your work over the years, I have used slick-carousel in the past and since moving to React this is the first time I have need a carousel so this was my first port of call.
This is a small one to remove the unease from my colleagues when they see 'slick-carousel' requires a peer-dependancy of jQuery... They say things like:
'Mark, I mean really, are you trying to add jQuery into our shiny new project?' 
or someone more junior else will say:
'Hey, I've add jQuery as per the output from the console on npm install, the carousel needs it!'
and of course I would feel better not having to see peer-dependancies not met on purpose :-)
Anyways, any chance of getting this in? The docs actually already say you need to install slick-carousel anyway for the CSS and font, so I …
=> Remove slick-carousel from peer and core dependancies and more to dev-dependancies in line with foundation styles

README.md
Adding this `charset="UTF-8"` attribute on the link tag prevents the dots from breaking.
=> slick carousel css uses UTF-8 encoding for the 'dots' 

src/mixins/helpers.js, src/mixins/trackHelper.js
When scrolling on variable width with infinite false, stop at the end of the last slide. This is useful if you don't want to show empty space in the carousel.
=> Variable Width Scrolling

src/mixins/helpers.js
I'm sorry I don't have a repro, but I have seen hundreds of our user stack traces in Sentry.  TypeError Cannot read property 'offsetHeight' of null in adaptHeight().  Maybe a rare timing scenario when the grid is initializing can cause this selector to return null.  
My change just defaults to empty object in this case so it doesn't hit a JavaScript error.
=> Add error handling to prevent errors

src/mixins/helpers.js
Center Padding currently uses parseInt to convert values to numbers, assuming it is a pixel value.  This change checks if it is a percentage value, and if so, calculates the percentage of the width it represents in pixels and adjusts accordingly
=> Center Padding Should Accept Percentage Values

README.md, examples/CenterMode.js, examples/__tests__/__snapshots__/SimpleSlider.test.js.snap, src/default-props.js, src/dots.js, src/inner-slider.js, src/mixins/event-handlers.js, src/mixins/helpers.js, src/mixins/trackHelper.js, src/slider.js, src/track.js, src/utils/trackUtils.js
**In progress**
Following are the changes to be mentioned:
- fixed slideWidth calculation approximation
- fixed unusual scrolls in focusOnSelect mode
- added appendDots method for customization of dots
- modified logic for handling odd/even cases where there were unusual scrolls in opposite direction
- implemented unslick feature properly
- fixed variableWidth issues like blank spaces at edges, improper alignment
- handling focus loss in case of fade=true
- responsive lazyloading bug fixed
- increased verticalswiping resistance from 4 to 10
=> merge dev to master

README.md, examples/__tests__/__snapshots__/SimpleSlider.test.js.snap, src/default-props.js, src/dots.js, src/inner-slider.js
Following on from [PR 1002](https://github.com/akiran/react-slick/pull/1002). This would add an attribute similar to that of appendDots in [slick](https://github.com/kenwheeler/slick).
It is done in the same style as `customPaging`, where users can provide a function for rendering the dots within a custom container. Meaning it should be both inline with the slick library, as well as inline with the coding standards of react-slick.
Thank-you for your consideration.
=> Add renderDots for custom rendering the dots

src/mixins/event-handlers.js
If you create a finite free swipable carousel, and try to scroll further the extremum slide, a JS error occurs:
> event-handlers.js:250 Uncaught TypeError: Cannot read property 'dataset' of undefined(…)
This PR fixes it. There is no tests, as I was unsuccessful to test a mix-in, even by trying to create a dummy element to deal with it. If you get some clue, I would be happy to add some. :)
=> Fix JS error when swipeToSlide but finite slide

src/mixins/helpers.js
The animation changes in #125 forgot to include the arrow function changes. Thus, the callback ID never gets set on the correct context. This can lead to `setState` getting called after the component has been unmounted.
=> Fixed animation timeout IDs never getting set/cleared

src/inner-slider.js
When the slider has the "asNavFor" configuration, the detection of the slide changes from one slider to the next does not always work. It might work always, or in other occassions, only on every other change.
The issue is that the second slider needs to be refreshed when the slide it points to is different to that of the parent slider, after this parent slider has updated.
This should fix https://github.com/akiran/react-slick/issues/1416
=> Fixing issue with asNavFor not detecting all slide changes

examples/__tests__/__snapshots__/CenterMode.test.js.snap, examples/__tests__/__snapshots__/FocusOnSelect.test.js.snap, examples/__tests__/__snapshots__/MultipleItems.test.js.snap, examples/__tests__/__snapshots__/SimpleSlider.test.js.snap, examples/__tests__/__snapshots__/UnevenSets.test.js.snap, src/inner-slider.js, src/slider.js
- https://github.com/reactjs/react-lifecycles-compat/issues/47#issuecomment-520236234
- https://github.com/akiran/react-slick/commit/97988e897750e1d8f7b10a86b655f50d75d38298#r34651934
=> fix: non-existed lifecycle UNSAFE_componentWillUnmount

src/inner-slider.js
There is no case componentDidMount that will be called on server side.
Good to not have the guard
=> refactor: no componentDidMount called on server

src/track.js
the last browsers requiring webkit vendor prefix is about 6years ago.
it's good enough to remove it.
=> refactor: remove deprecated vendor prefix

src/slider.js
This PR will fix this [issue-1663](https://github.com/akiran/react-slick/issues/1663)
Due to parent settings variable, newChildren was always giving blank children. In the case of unslick, we should return direct children.
=> default children return in case of unslick

src/inner-slider.js
Fix #1356 
`document.querySelectorAll(".slick-slide img")` selector will select all images under `.slick-slide` and add onload event on those images.  if there are multiple react-slick instance on the same page, the image.onload event may be handled by other react-slick instance . 
This commit aims to fix the issue by searching `".slick-slide img"` in the list reference instead of document.
=> fix: to handle image.onload event correctly

src/inner-slider.js, src/track.js, src/utils/innerSliderUtils.js
=> Got rid of ReactDOM.findDOMNode (#1406)

src/inner-slider.js
In some cases, for instance while running some tests via storyshot, we can get a blocker with this error message:
`Error: Uncaught [TypeError: Cannot read property 'querySelectorAll' of undefined]`
Adding `this.list &&` at the beginning of this test will avoid such of issues and let pass well the tests
I would really appreciate that fix to be able to move forward from `0.25.2` of react-slick to the latest version
Thanks
=> Need to enforce images list validation

src/inner-slider.js
I found an issue due to a missing argument in the previous click handler invocation. Thanks.
=> Fixed issue with image click event

CONTRIBUTING.md
In CONTRIBUTING.md there's this link: "[How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)."
This link is now broken, so I changed to:  [How to Contribute to an Open Source Project on GitHub](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github).
=> Correct "Your First Contribution" link in CONTRIBUTION.md

package.json
`@testing-library/user-event` is not needed in production.
=> Move testing dependency to devDependencies
