README.md
It needs completing but i'm not sure what the rest do
=> Added table to show what properties do what

lib/initial-state.js, lib/mixins/event-handlers.js, lib/mixins/helpers.js
Now waits *n* ms since last action. Any slide transition resets the timer.
=> Fix autoplay behaviour

lib/default-props.js, lib/inner-slider.jsx
This allows you to pass in custom next and prev elements as props.
=> Adding the ability to specify custom next and prev arrow elements

docs/demos.jsx, docs/index.html, lib/initial-state.js, lib/inner-slider.jsx, lib/mixins/helpers.js
=> [WIP] Fix warnings in demos caused by render function being not pure

README.md, package.json, src/default-props.js, src/initial-state.js, src/inner-slider.jsx, src/mixins/event-handlers.js, src/mixins/helpers.js, src/mixins/trackHelper.js, src/slider.jsx, src/track.jsx
=> Implement new feautures and fix few bugs

src/mixins/trackHelper.js
=> Update to add support for IE9 transforms via `msTransform`

README.md, src/dots.jsx, src/inner-slider.jsx, src/mixins/helpers.js, src/mixins/trackHelper.js
- Add matchMedia polyfill for README
- Fix addEventListener issue
- Fix empty array map issue
=> Fix IE8 Compatibility

docs/_style.scss, package.json, src/mixins/helpers.js
Cleaned git process problems of PR https://github.com/akiran/react-slick/pull/124
@krasimir  I created a new branch and merged your PR in to it.
That cleaned unnecessary file changed issue.
I am merging this branch and making a release now.
Thanks for your contributions
=> Current slide

package.json
=> updates package.json to support react 0.13 and 0.14

src/mixins/helpers.js
A simple condition on `this.props.rtl` to choose between adding or subtracting to determine the next slide.
=> Autoplay ignores rtl #197

test/basic.jsx
There is testing infrastructure, but not yet any tests running.
This makes changes scary, as we worry about breaking things.  This is
some very basic testing of rendering and tearing down the examples.
Ideas to expand on this:
* Simulate Clicks and other expected user interactions.
* Test common patterns people actually use.
* Test alt versions of React that we want to support.
=> Add some basic testing.

src/arrows.jsx
Fixes https://github.com/akiran/react-slick/issues/257
=> removes arrow refs

src/mixins/helpers.js
close #285 and ant-design/ant-design#1397
=> Fix extra setInterval when autoplay

docs/demos.jsx, src/arrows.jsx
There are merge conflicts in #293
Created a new PR with those changes
=> Use React.cloneElement for custom element

src/mixins/helpers.js
https://github.com/akiran/react-slick/pull/287#issuecomment-216513490
@akiran
=> Fix pauseOnHover introduced by #287

package.json
=> remove deprecated phantomjs package - phantomjs-prebuilt is installed

README.md
=> add `pauseOnHover` to readme

src/arrows.jsx, src/dots.jsx
* Fix undefined event calling preventDefault when using keyboard to navigate.
* Fix dots not selecting properly when initialSlide is set and slidesToScroll isn't 1
=> Keyboard error and dot selection fixes

README.md, src/default-props.js, src/inner-slider.jsx, src/mixins/event-handlers.js, src/mixins/helpers.js, src/track.jsx
Add tab and arrow key navigation
=> Added accessibility (tab and arrow key navigation)

README.md, docs/demos.jsx, examples/PreviousNextMethods.js, src/mixins/event-handlers.js, src/slider.jsx
It can be useful to create custom controls or change slide on events (like key, touch and etc.)
=> Expose previous and next function

src/arrows.jsx
Fixes https://github.com/akiran/react-slick/issues/271
Signed-off-by: Suhaib Khan <suheb.work@gmail.com>
=> Fixing next button disable state.

src/mixins/event-handlers.js
See issue #480 for more details.
=> Fix #480: Prevent default event when swipeToSlide and vertical used

src/arrows.js, src/mixins/helpers.js
fixes #505 
extracts some logic to a helper, and uses it in two places.
=> prevent autoplay transition when there are no extra cards #505

README.md
Updates the demo URL in the readme to match the repository's URL on GitHub
=> Update README.md with correct demo link

package.json, src/slider.js
Fixes #721 
The code is based on the way this check was done previously in [react-responsive-mixin](https://github.com/akiran/react-responsive-mixin/blob/f9571367ae2fba244c7211e529d9614ff41ed012/index.js#L2)
=> Check if in the browser before loading enquire.js

docs/demos.jsx, examples/NoSlider.js, src/mixins/helpers.js
Hi, 
When api was returning with no data it was crashing so by this fix it wont crash anymore
Thanks
=> when there is no inner children arrived avoid errors

src/initial-state.js, src/mixins/event-handlers.js
Port of the same fix in slick: https://github.com/kenwheeler/slick/pull/2521/files
=> [fix] https://github.com/akiran/react-slick/issues/670

src/mixins/helpers.js
This fixes the slider not autoplaying after a resize.
=> Fix wrong if statement related with autoplay and resize

package.json
=> Only publish build files for a leaner module

README.md
Also updated a few descriptions & general styling.
=> Update README with default props

README.md
Add installation guidelines for yarn
=> [Readme] Add installation guidelines for yarn

README.md, package.json, src/default-props.js, src/inner-slider.js, src/mixins/helpers.js, src/mixins/trackHelper.js, src/slider.js
Includes changes that several open PRs request and some commits that I made.
=> merge dev changes into master

src/mixins/event-handlers.js, src/mixins/helpers.js
i found problem at rtl option,
when drag a object, that moving in opposite direction,
you can check at example
=> fix, a moving in opposite direction on drag event at rtl option

src/track.js
=> fix property fade messed up onClick action on slides

src/slider.js
This code fix #777 issue. Now it works like `max-width` media query described in readme.
=> Fix responsive behavior. Issue #777

src/mixins/helpers.js
close ant-design/ant-design#3659
The element'width will be affected by `transform: scale(xxx)`.
https://codepen.io/afc163/pen/RxNbQq?editors=0110
=> Fix slide width issue by transform scale

README.md
fixing bug doc's code that leads to invariant violation error given react-slick is using export default now
=> fixing bug doc's code

CONTRIBUTING.md
=> Correct contributors link in CONTRIBUTING.md

src/inner-slider.js
=> Fix NodeList forEach under chrome 51 or below

README.md, src/inner-slider.js, src/utils/innerSliderUtils.js
*Changes to mention*
- fixed 'setState on unmounted component' warning
- fixed 'querySelector on undefined' error
=> fix basic ssr warnings and errors

gulpfile.js, package.json
- Dependencies add - opn (dev)
=> open server url on webpack dev server start

examples/SlideChangeHooks.js, src/inner-slider.js
Fixes #1216 
Could use an updated test in `__tests__/beforeChange.test.js`
=> Before change current slide

package.json
=> Move prettier to devDependencies

src/inner-slider.js, src/slider.js
Added style props to the component allowing the user to pass inline styles. Fixed #1586
=> Added style props to the component allowing to user to pass inline styles

.github/FUNDING.yml
Added the necessary configuration file required for the button to show up :+1:
=> meta: Enables sponsor button

CONTRIBUTING.md
Corrected 2 broken links to issues page in CONTRIBUTING.md
=> #1749 Correct issue link in CONTRIBUTING.md

src/utils/innerSliderUtils.js
=> Remove unused argument

__tests__/afterChange.test.js
I fixed the afterChange test by adding setTimeOut function to simulate the delay.
=> fix the afterChange-test

src/utils/innerSliderUtils.js
Thanks for great library 👍 
-
from this commit https://github.com/akiran/react-slick/commit/38d16a9f567d37ee6c6a6cfdba6c3db76bfaed9d only supports horizontal mode, I added for vertical mode, we also need it in vertical mode.
=> Support disable bounce for vertical mode

examples/AdaptiveHeight.js
* The class component was updated by a functional component.
* var was changed to const
=> Upgrade AdaptiveHeight to functional component

docs/index.js, docs/single-demo.js, package.json
Update proejct to support React 19. This includes use of `createRoot` function in render demo and update `react`, `react-dom` and `@testing-library/react` dependencies.
=> Updated to React 19
